### ISSUE TITLE
Add a guideline in the camera view to help users capture the road properly

### ISSUE THREAD

**Issue by udiyan** [ydrive/citysynth-android-issues#15]
Propose adding a line at the 1/3 mark to indicate the “road horizon”, so users get a proper mix of road and the rest of the world. This is a poor man’s solution to the problem
Of users pointing the camera too far up or too far down.

**Comment by fpanjevic** [comment]
Proposal below, feedback welcome.

![Screenshot_2022-05-15-19-35-55-997_ai ydrive CityBuilder](https://user-images.githubusercontent.com/10568373/168563963-ac2ea801-5fb6-453b-8b99-d2c05d830a90.jpg)
![Screenshot_2022-05-15-19-37-17-773_ai ydrive CityBuilder](https://user-images.githubusercontent.com/10568373/168563975-561c32bb-1449-40e9-9f59-c9e8ad1d019c.jpg)
![Screenshot_2022-05-15-19-38-22-521_ai ydrive CityBuilder](https://user-images.githubusercontent.com/10568373/168563980-5c812765-86a5-45ae-8e2e-6b9c10ff5c7e.jpg)

**Comment by fpanjevic** [comment]
Perspectives not matching is triggering my OCD, if we proceed with this idea that needs to be corrected.

**Comment by fpanjevic** [comment]
From @NikolaJov96 

> Like the horizon and the perspective lines.
> Not 100% sure about the dashed line in the middle, it may be understood as a suggestion to drive in the middle of the road while not staying in one lane.
